### ISSUE TITLE
実装コードに関する質問

### ISSUE THREAD

**Issue by makkimaki** [makaishi2/python_bayes_intro#2]
もしお時間ありましたら本書に関する質問にご回答いただければ幸いです。

p.152 コード 5.4.13, 18-20行目に以下の実装があります
```
delta = 0.1
y0 = norm(x, mean_mu0, mean_sigma0) * delta / n_components
y1 = norm(x, mean_mu1, mean_sigma1) * delta / n_components
```

ここの` * delta / n_components`の部分の果たす役割がわかりません。どういった導出でしょうか。

なんとなくですが、２クラスの各々のデータが同数であることを仮定して成り立っている感じがしており、もしクラスバランスが異なるときはどうするべきか、知りたかったです。

**Comment by makaishi2** [comment]
ご質問いただきありがとうございます。
確かにここはわかりにくい箇所であり、なんらかの説明があった方がよかったと思っています。下記のサポートサイトFAQに、いただいたご質問への回答を一通り記載したつもりです。
ご確認いただければと思います。

https://github.com/makaishi2/python_bayes_intro/blob/main/refs/faqs.md

**Comment by makkimaki** [comment]
ありがとうございました！
