### ISSUE TITLE
正誤表関連　追加

### ISSUE THREAD

**Issue by makkimaki** [makaishi2/python_bayes_intro#3]
再度、正誤表について追加させてください。

p.164 表6.1.1、山田さんの改善後のページB、表示数について
```
誤：1500
正：1600
```
になるのではないかと思います。
この章の他のコードを拝見すると、表示数を1600とした実装に統一されていました。適宜ご確認お願いいたします。

**Comment by makaishi2** [comment]
ありがとうございます。ご指摘のとおりなので、正誤訂正に反映しました。
 引き続きよろしくお願いいたします。

https://github.com/makaishi2/python_bayes_intro/blob/main/refs/errors.md
