### ISSUE TITLE
5.4.6 潜在変数の確率分布における潜在変数sのサンプル値の決定方法について

### ISSUE THREAD

**Issue by iharuto** [makaishi2/python_bayes_intro#4]
こんにちは。二点お聞きしたいことがあります。
この節では各サンプルがversicolorに属するのかvirginicaに属するのかをベルヌーイ分布からサンプリングされた値から判断できることを示唆していました。ここでベルヌーイ分布の母数pをサンプルの数だけ個別に用意していないのにも関わらず、サンプルごとに0か1か大まかに分類できていたのはなぜでしょうか。pがエポック毎に一様分布から1つサンプリングされるのであれば0、1のラベルはサンプルに関係なくランダムに付与されるのではないかと思いました。

もう一つの質問は本節ではsigmaの代わりにtauを使って分布の広がり具合を表していましたがsigmaを使うと失敗する原因は何でしょうか?

よろしくお願いします。

**Comment by makaishi2** [comment]
ご質問いただき、ありがとうございます。
やや複雑な質問であるため、qiitaで実装コード付きで説明しました。
回答には一部不十分な点もありますが、その点はご理解いただければと思います。
よろしくお願いいたします。

https://qiita.com/makaishi2/items/2ce59c2562537b92f383
